#!/usr/bin/env bash
# configure a serverto listening on port 80 of all server's active IPV4 IPs
sudo sed -i "s/8080/80/" /etc/nginx/sites-available/default
sudo service nginx restart
echo "" | sudo dd staus=none of=/run/nginx.pid
