#!/usr/bin/env bash
# change localhost to 127.0.0.2
# chnage facebook to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
